error check

diff --git a/src/expose_port b/src/expose_port
--- a/src/expose_port
+++ b/src/expose_port
@@ -108,14 +108,24 @@ else
 
     #Extract value before ":" -> REMOTE_UNAME @ REMOTE_IP
     VALUE_BEFORE=`echo "$REMOTE_DETAILS" | awk -F: '{print $1}'`  
- 
-    #Extract string after @ -> Server IP
-    REMOTE_IP=`echo $VALUE_BEFORE | awk -F@ '{print $2}'`
-   
+    
     #Extract string before @ -> User Name
     REMOTE_UNAME=`echo $VALUE_BEFORE | awk -F@ '{print $1}'`
 
-  
+    if [ -z $REMOTE_UNAME ]; then
+        echo " Error: Invalid Server Details"
+        exit 1
+    fi
+
+
+    #Extract string after @ -> Server IP
+    REMOTE_IP=`echo $VALUE_BEFORE| awk -F@ '{print $2}'`
+    
+    if [ -z $REMOTE_IP ]; then
+        echo " Error: Invalid Server Details"
+        exit 1
+    fi
+
     #Reset Remote Details 
     REMOTE_DETAILS="${REMOTE_UNAME}@${REMOTE_IP}:${REMOTE_SSH_PORT}"   
 
