expose port

diff --git a/src/expose_port b/src/expose_port
--- a/src/expose_port
+++ b/src/expose_port
@@ -1,3 +1,5 @@
+#!/bin/bash
+
 : '
 	Utility to Expose Local Device Port to Internet
 	
@@ -5,44 +7,58 @@
 			:	vikiworks.io
 '
 
-LOCAL_PORT=""
 REMOTE_IP=""
 REMOTE_UNAME=""
 REMOTE_PASS=''
 REMOTE_SSH_PORT=""
 REMOTE_DETAILS=""
 
+THIS_USER=$USER
+
+LOCAL_PORT=""
+
+#RUN_BACKGROUND="true"
+
 #Single Line Usage:
-#./expose_port.sh <local_port_to_expose> <username>@<remote_ip> <remote_ssh_port>
-#./expose_port.sh 22 testuser@2.3.4.5 
+#./expose_port <local_port_to_expose> <username>@<remote_ip> <remote_ssh_port>
+#./expose_port 80 testuser@2.3.4.5 
 
 # Prerequisite check
 
 which sshpass > /dev/null 
 if [ $? -ne 0 ]; then
 	echo " [ error ] ( sshpass ) is not installed in this system, Install and try again"
+    exit 1
 fi
 
 which ssh > /dev/null 
 if [ $? -ne 0 ]; then
 	echo " [ error ] ( ssh ) is not installed in this system, Install and try again"
+    exit 1
 fi
 
+RS0=" Enter local port to expose                 : "
+RS1=" Enter jump server IP ADDRESS / DOMAIN NAME : " 
+RS2=" Enter remote server username               : "
+RS3=" Enter remote server password               : "
+RS4=" Enter remote server ssh port               : "
+KS1=" Remote Host Details                        :"
+HLP=" Press ( ctrl + c ) to exit application      "
 
+if [ $# -lt 1 ]; then 
+	echo
+	echo "$HLP"
+	echo
+	echo
 
-if [ $# -lt 2 ]; then 
-	echo
-	echo
-	echo " Press ( ctrl + c ) to exit application "
-	echo
-	echo
 	while [ 1 ]
 	do
-		if [[ ! -z $LOCAL_PORT ]]; then
-	        break
-	    fi
-	    read -p " Enter local port number to expose to the world   : " LOCAL_PORT    </dev/tty
+    	if [[ ! -z $LOCAL_PORT ]]; then
+        	break
+    	fi
+    	read -p "$RS0" LOCAL_PORT  </dev/tty
 	done
+
 
 
 	while [ 1 ]
@@ -50,7 +66,7 @@ if [ $# -lt 2 ]; then
     	if [[ ! -z $REMOTE_IP ]]; then
         	break
     	fi
-    	read -p " Enter remote server [ ip address / domain name ] : " REMOTE_IP     </dev/tty
+    	read -p "$RS1" REMOTE_IP     </dev/tty
 	done
 
 	while [ 1 ]
@@ -58,39 +74,62 @@ if [ $# -lt 2 ]; then
     	if [[ ! -z $REMOTE_UNAME ]]; then
         	break
     	fi
-    	read -p " Enter remote server username                     : " REMOTE_UNAME  </dev/tty
+    	read -p "$RS2" REMOTE_UNAME  </dev/tty
 	done
+   
+ 	while [ 1 ]
+	do
+    	if [[ ! -z $REMOTE_SSH_PORT ]]; then
+        	break
+    	fi
+    	read -p "$RS4" REMOTE_SSH_PORT  </dev/tty
+	done
+   
+
+
+    REMOTE_DETAILS="${REMOTE_UNAME}@${REMOTE_IP}:$REMOTE_SSH_PORT"
 
 else
-	
-	if [ ! -z "$1" ]; then
-    	LOCAL_PORT=$1
-	fi
+    echo 	
+    if [ ! -z "$1" ]; then
+        LOCAL_PORT=$1
+    fi	
 
 	if [ ! -z "$2" ]; then
     	REMOTE_DETAILS=$2
 	fi
 	
-	if [ ! -z "$3" ]; then
-    	REMOTE_SSH_PORT=$3
-	else
-		REMOTE_SSH_PORT=22
-	fi
-	echo
-	echo " Local Port 					  : $LOCAL_PORT"
-	echo " Remote Host Details 				  : $REMOTE_DETAILS -p $REMOTE_SSH_PORT"
+    #Extract value after ":" -> Server Port
+    REMOTE_SSH_PORT=`echo "$REMOTE_DETAILS" | awk -F: '{print $2}'`
+ 
+    if [ -z $REMOTE_SSH_PORT ]; then
+        REMOTE_SSH_PORT=22
+    fi
+
+    #Extract value before ":" -> REMOTE_UNAME @ REMOTE_IP
+    VALUE_BEFORE=`echo "$REMOTE_DETAILS" | awk -F: '{print $1}'`  
+ 
+    #Extract string after @ -> Server IP
+    REMOTE_IP=`echo $VALUE_BEFORE | awk -F@ '{print $2}'`
+   
+    #Extract string before @ -> User Name
+    REMOTE_UNAME=`echo $VALUE_BEFORE | awk -F@ '{print $1}'`
+
+  
+    #Reset Remote Details 
+    REMOTE_DETAILS="${REMOTE_UNAME}@${REMOTE_IP}:${REMOTE_SSH_PORT}"   
+
 fi
 
-if [ -z "$REMOTE_SSH_PORT" ]; then
-	REMOTE_SSH_PORT=22
-fi
+echo
+echo "$KS1 $REMOTE_DETAILS"
 
 while [ 1 ]
 do
 	if [[ ! -z $REMOTE_PASS ]]; then
 		break
 	fi
-	read -sp " Enter remote server password                     : " REMOTE_PASS
+	read -sp "$RS3" REMOTE_PASS
 done
 
 echo 
@@ -117,19 +156,15 @@ do
 
     touch $ERROR_LOG
    
-	if [[ ! -z $REMOTE_DETAILS ]]; then 
-		sshpass -p $REMOTE_PASS  ssh -o StrictHostKeyChecking=no -f -N  -R $INCOMING_PORT:localhost:$LOCAL_PORT -p $REMOTE_SSH_PORT $REMOTE_DETAILS 2> $ERROR_LOG
-	else
-		sshpass -p $REMOTE_PASS  ssh -o StrictHostKeyChecking=no -f -N  -R $INCOMING_PORT:localhost:$LOCAL_PORT -p $REMOTE_SSH_PORT $REMOTE_UNAME@$REMOTE_IP 2> $ERROR_LOG
-    fi
-
+	sshpass -p $REMOTE_PASS  ssh -o StrictHostKeyChecking=no -f -N  -R $INCOMING_PORT:localhost:$LOCAL_PORT -p $REMOTE_SSH_PORT ${REMOTE_UNAME}@${REMOTE_IP} 2> $ERROR_LOG
+	
     #Check Command Exit Status
     if [ $? -ne 0 ]; then
         echo
         echo
         echo "[ status ] Execution Error : "
         echo
-        printf "\t( execution failure ) ssh -f -N  -R $INCOMING_PORT:localhost:$LOCAL_PORT -p 22 $REMOTE_UNAME@$REMOTE_IP 2> $ERROR_LOG"
+        printf "\t( execution failure ) ssh -o StrictHostKeyChecking=no -f -N  -R $INCOMING_PORT:localhost:$LOCAL_PORT -p $REMOTE_SSH_PORT ${REMOTE_UNAME}@${REMOTE_IP} 2> $ERROR_LOG"
         echo
         echo
     	rm $ERROR_LOG 2> /dev/null
@@ -161,17 +196,41 @@ done
 
 echo ""
 echo ""
-echo "#########################################################################################"
+echo "####################################################################"
 echo ""
 echo ""
-echo " Local Port ( $LOCAL_PORT ) successfully exposed to the world!!"
+echo " You can access port ( $LOCAL_PORT ) of this device using the following details, "
 echo ""
 echo ""
-echo " You can access tcp port ( $LOCAL_PORT ) on this device using [ IP/DNS : $REMOTE_IP ] [ PORT : $INCOMING_PORT ]"
+echo " USER NAME ( optional )     :  $THIS_USER"
+echo " DOMAIN NAME                :  $REMOTE_IP"
+echo " PORT                       :  $INCOMING_PORT "
 echo ""
 echo ""
-echo "#########################################################################################"
+echo "####################################################################"
 echo ""
 echo ""
 
 rm $ERROR_LOG 2> /dev/null
+
+if [ "$RUN_BACKGROUND" = "true" ]; then
+    exit 0
+fi
+
+signal_handler () {
+    trap SIGINT   
+    echo                
+    echo " stopping service running on port -> $INCOMING_PORT"    
+    ps -ef | grep "ssh" | grep 'localhost' | grep "$INCOMING_PORT" | grep -v "grep" | awk '{print $2}' | xargs -I{} kill -9 {}   
+    echo " Exitting expose_port"    
+    exit                     
+}
+
+trap "signal_handler" INT            # Set up SIGINT trap to call function.
+echo "$HLP"
+printf " "
+while [ 1 ]
+do
+    sleep 1
+done  
+
